
export const STATE_LOADED = 'STATE_LOADED';

export const SET_SHOWED_GROUP = 'SET_SHOWED_GROUP';

export const ADD_PROJECT = 'ADD_PROJECT';

export const ADD_GROUP = 'ADD_GROUP';

export const ADD_TASK = 'ADD_TASK';

export const ADD_TAG = 'ADD_TAG';

export const UPDATE_TASK_ADD_TAG = 'UPDATE_TASK_ADD_TAG';

export const UPDATE_TASK_DELETE_TAG = 'UPDATE_TASK_DELETE_TAG';

export const UPDATE_TASK_CHANGE_STATUS = 'UPDATE_TASK_CHANGE_STATUS';