
export const STATE_LOADED = 'STATE_LOADED';

export const SET_SHOWED_GROUP = 'SET_SHOWED_GROUP';

export const ADD_PROJECT = 'ADD_PROJECT';

export const ADD_GROUP = 'ADD_GROUP';

export const ADD_TASK = 'ADD_TASK';

export const ADD_TAG = 'ADD_TAG';

export const UPDATE_TASK_ADD_TAG = 'UPDATE_TASK_ADD_TAG';

export const UPDATE_TASK_DELETE_TAG = 'UPDATE_TASK_DELETE_TAG';

export const UPDATE_TASK_CHANGE_STATUS = 'UPDATE_TASK_CHANGE_STATUS';

export const UPDATE_TASK_ADD_ASSIGNED = 'UPDATE_TASK_ADD_ASSIGNED';

export const UPDATE_TASK_DELETE_ASSIGNED = 'UPDATE_TASK_DELETE_ASSIGNED';

export const UPDATE_TASK_ADD_DATE_DUE = 'UPDATE_TASK_ADD_DATE_DUE';

export const UPDATE_TASK_ADD_COMMENT = 'UPDATE_TASK_ADD_COMMENT';

export const UPDATE_TASK_DELETE_COMMENT = 'UPDATE_TASK_DELETE_COMMENT';

export const ADD_FILE = 'ADD_FILE';

export const UPDATE_TASK_ADD_FILE = 'UPDATE_TASK_ADD_FILE';

export const UPDATE_COMMENT_ADD_FILE = 'UPDATE_COMMENT_ADD_FILE';

export const UPDATE_COMMENT_DELETE_FILE = 'UPDATE_COMMENT_DELETE_FILE';