
export const PROJECTS_LOADED = 'PROJECTS_LOADED';

export const GROUPS_LOADED = 'GROUPS_LOADED';

export const TASKS_LOADED = 'TASKS_LOADED';

export const USERS_LOADED = 'USERS_LOADED';

export const TAGS_LOADED = 'TAGS_LOADED';

export const COMMENTS_LOADED = 'COMMENTS_LOADED';

export const FILES_LOADED = 'FILES_LOADED';

export const LOGIN_USER = 'LOGIN_USER';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_SHOWED_GROUP = 'SET_SHOWED_GROUP';

export const ADD_PROJECT = 'ADD_PROJECT';

export const ADD_GROUP = 'ADD_GROUP';

export const UPDATE_GROUP_SET_DONE = 'UPDATE_GROUP_SET_DONE';

export const ADD_TASK = 'ADD_TASK';

export const ADD_TAG = 'ADD_TAG';

export const ADD_COMMENT = 'ADD_COMMENT';

export const DELETE_COMMENT = 'DELETE_COMMENT';

export const UPDATE_TASK_ADD_TAG = 'UPDATE_TASK_ADD_TAG';

export const UPDATE_TASK_SET_DONE = 'UPDATE_TASK_SET_DONE';

export const UPDATE_TASK_DELETE_TAG = 'UPDATE_TASK_DELETE_TAG';

export const UPDATE_TASK_CHANGE_STATUS = 'UPDATE_TASK_CHANGE_STATUS';

export const UPDATE_TASK_ADD_ASSIGNED = 'UPDATE_TASK_ADD_ASSIGNED';

export const UPDATE_TASK_DELETE_ASSIGNED = 'UPDATE_TASK_DELETE_ASSIGNED';

export const UPDATE_TASK_ADD_DATE_DUE = 'UPDATE_TASK_ADD_DATE_DUE';

export const UPDATE_TASK_ADD_COMMENT = 'UPDATE_TASK_ADD_COMMENT';

export const UPDATE_TASK_DELETE_COMMENT = 'UPDATE_TASK_DELETE_COMMENT';

export const ADD_FILE = 'ADD_FILE';

export const DELETE_FILE = 'DELETE_FILE';

export const UPDATE_TASK_ADD_FILE = 'UPDATE_TASK_ADD_FILE';

export const UPDATE_COMMENT_ADD_FILE = 'UPDATE_COMMENT_ADD_FILE';

export const UPDATE_COMMENT_DELETE_FILE = 'UPDATE_COMMENT_DELETE_FILE';